Repository Open-Eye-Im-Developer/MoGakGo-BE, pull requests merged in 2024-02, with the labels that each got.

#4 Feat/#3 security setting
  core/build.gradle
  core/core-jpa/build.gradle
  core/core-jpa/src/main/java/io/oeid/core_jpa/configuration/QueryDSLConfiguration.java
  core/core-security/build.gradle
  core/core-security/src/main/java/io/oeid/core_security/CoreSecurityApplication.java
  core/core-security/src/main/java/io/oeid/core_security/configuration/SecurityConfiguration.java
  core/core-security/src/main/java/io/oeid/core_security/jwt/JwtAccessDeniedHandler.java
  core/core-security/src/main/java/io/oeid/core_security/jwt/JwtAuthenticationEntryPoint.java
  core/core-security/src/main/java/io/oeid/core_security/jwt/JwtAuthenticationFilter.java
  core/core-security/src/main/java/io/oeid/core_security/jwt/JwtAuthenticationToken.java
  core/core-security/src/main/java/io/oeid/core_security/jwt/JwtHelper.java
  core/core-security/src/main/java/io/oeid/core_security/jwt/JwtToken.java
  core/core-security/src/main/java/io/oeid/core_security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  core/core-security/src/main/java/io/oeid/core_security/oauth/service/CustomOAuth2UserService.java
  core/core-security/src/main/java/io/oeid/core_security/properties/JwtProperties.java
  domain/build.gradle
  domain/domain-user/build.gradle
  domain/domain-user/src/main/java/io/oeid/domain_user/domain/Role.java
  domain/domain-user/src/main/java/io/oeid/domain_user/domain/User.java
  domain/domain-user/src/main/java/io/oeid/domain_user/infrastructure/UserJpaRepository.java
  settings.gradle
Labels: 🧹 Chore, ⭐️ Feat

#14 Feat/#11 user domain
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/UserDevelopLanguageTag.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/UserWantedJobTag.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/enums/DevelopLanguage.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/enums/WantedJob.java
  src/main/java/io/oeid/mogakgo/domain/user/infrastructure/UserDevelopLanguageTagJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/user/infrastructure/UserWantedJobTagJpaRepository.java
Labels: ⭐️ Feat

#15 [FEAT] Notification Domain 기능 구현
  src/main/java/io/oeid/mogakgo/domain/notification/domain/Notification.java
  src/main/java/io/oeid/mogakgo/domain/notification/domain/enums/NotificationTag.java
  src/main/java/io/oeid/mogakgo/domain/notification/infrastructure/NotificationJpaRepository.java
Labels: ⭐️ Feat

#26 Swagger test
  build.gradle
  src/main/java/io/oeid/mogakgo/core/configuration/SecurityConfiguration.java
  src/main/java/io/oeid/mogakgo/core/configuration/SwaggerConfig.java
  src/main/java/io/oeid/mogakgo/core/properties/JwtProperties.java
  src/main/java/io/oeid/mogakgo/core/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/io/oeid/mogakgo/core/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/io/oeid/mogakgo/core/security/jwt/JwtAuthenticationFilter.java
  src/main/java/io/oeid/mogakgo/core/security/jwt/JwtAuthenticationToken.java
  src/main/java/io/oeid/mogakgo/core/security/jwt/JwtHelper.java
  src/main/java/io/oeid/mogakgo/core/security/jwt/JwtToken.java
  src/main/java/io/oeid/mogakgo/core/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/io/oeid/mogakgo/core/security/oauth/service/CustomOAuth2UserService.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
Labels: 🚀 Infra, 🎯 MVP1

#27 Swagger test (#26)
  build.gradle
  src/main/java/io/oeid/mogakgo/core/configuration/SecurityConfiguration.java
  src/main/java/io/oeid/mogakgo/core/configuration/SwaggerConfig.java
  src/main/java/io/oeid/mogakgo/core/properties/JwtProperties.java
  src/main/java/io/oeid/mogakgo/core/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/io/oeid/mogakgo/core/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/io/oeid/mogakgo/core/security/jwt/JwtAuthenticationFilter.java
  src/main/java/io/oeid/mogakgo/core/security/jwt/JwtAuthenticationToken.java
  src/main/java/io/oeid/mogakgo/core/security/jwt/JwtHelper.java
  src/main/java/io/oeid/mogakgo/core/security/jwt/JwtToken.java
  src/main/java/io/oeid/mogakgo/core/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/io/oeid/mogakgo/core/security/oauth/service/CustomOAuth2UserService.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
Labels: 🚀 Infra, 🎯 MVP1

#28 [FEAT] Project 도메인 개발 (#10) (진행중)
  src/main/java/io/oeid/mogakgo/domain/project/domain/Project.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/enums/ProjectStatus.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectJpaRepository.java
Labels: ⭐️ Feat

#31 Refact/#29 project entity
  src/main/java/io/oeid/mogakgo/common/base/BaseTimeEntity.java
  src/main/java/io/oeid/mogakgo/core/configuration/JpaConfig.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/Project.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/Project.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/enums/ProjectStatus.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/vo/CreatorInfo.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/vo/MeetingInfo.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectJpaRepository.java
Labels: 🔄 Refactor, 🎯 MVP1

#35 [FEAT] 공통 Error Handler, code 기능 구현
  src/main/java/io/oeid/mogakgo/exception/GlobalExceptionHandler.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode404.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode500.java
  src/main/java/io/oeid/mogakgo/exception/dto/ErrorResponse.java
  src/main/java/io/oeid/mogakgo/exception/exceptionClass/CustomException.java
Labels: ⭐️ Feat, 🎯 MVP1

#47 Refact/#46 errorcode
  src/main/java/io/oeid/mogakgo/exception/GlobalExceptionHandler.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode404.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode500.java
  src/main/java/io/oeid/mogakgo/exception/exception_class/CustomException.java
Labels: 🔄 Refactor, 🎯 MVP1

#54 [FEAT] 서비스 지역에 대한 법정동 코드 관리 위한 Enum 구현
  src/main/java/io/oeid/mogakgo/domain/geo/domain/enums/Region.java
Labels: ⭐️ Feat, 🎯 MVP1

#59 [CHORE] firebase-admin 의존성 추가
  build.gradle
Labels: 🧹 Chore, 🎯 MVP1

#60 [FEAT] Kakao Map API를 이용해 좌표 - 법정동 코드 변환 기능 개발
  build.gradle
  src/main/java/io/oeid/mogakgo/MogakGoApplication.java
  src/main/java/io/oeid/mogakgo/core/properties/KakaoProperties.java
  src/main/java/io/oeid/mogakgo/domain/geo/application/GeoService.java
  src/main/java/io/oeid/mogakgo/domain/geo/feign/KakaoFeignClient.java
  src/main/java/io/oeid/mogakgo/domain/geo/feign/dto/AddressDocument.java
  src/main/java/io/oeid/mogakgo/domain/geo/feign/dto/AddressInfoDto.java
Labels: ⭐️ Feat, 🎯 MVP1

#57 Feat/#3 security settings
  build.gradle
  src/main/java/io/oeid/mogakgo/common/annotation/UserId.java
  src/main/java/io/oeid/mogakgo/common/resolver/UserIdAnnotationResolver.java
  src/main/java/io/oeid/mogakgo/core/configuration/SecurityConfig.java
  src/main/java/io/oeid/mogakgo/core/configuration/WebMvcConfig.java
  src/main/java/io/oeid/mogakgo/core/properties/JwtProperties.java
  src/main/java/io/oeid/mogakgo/domain/auth/exception/AuthException.java
  src/main/java/io/oeid/mogakgo/domain/auth/jwt/JwtAccessDeniedHandler.java
  src/main/java/io/oeid/mogakgo/domain/auth/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/io/oeid/mogakgo/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/io/oeid/mogakgo/domain/auth/jwt/JwtAuthenticationToken.java
  src/main/java/io/oeid/mogakgo/domain/auth/jwt/JwtHelper.java
  src/main/java/io/oeid/mogakgo/domain/auth/jwt/JwtRedisDao.java
  src/main/java/io/oeid/mogakgo/domain/auth/jwt/JwtToken.java
  src/main/java/io/oeid/mogakgo/domain/auth/oauth/GithubOAuth2UserService.java
  src/main/java/io/oeid/mogakgo/domain/auth/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/AuthController.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/dto/res/AuthAccessTokenResponse.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/dto/res/AuthLoginUrlResponse.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/vo/CreatorInfo.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
  src/main/java/io/oeid/mogakgo/domain/user/infrastructure/UserJpaRepository.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode401.java
Labels: 🧹 Chore, ⭐️ Feat, 🎯 MVP1

#61 Feat/#32 project card 생성, 삭제 구현
  build.gradle
  src/main/java/io/oeid/mogakgo/common/base/BaseTimeEntity.java
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerProjectErrorExamples.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerUserErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/auth/jwt/JwtHelper.java
  src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/Project.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/ProjectTag.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/vo/CreatorInfo.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/vo/MeetingInfo.java
  src/main/java/io/oeid/mogakgo/domain/project/exception/ProjectException.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/ProjectController.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/req/ProjectCreateReq.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/req/ProjectTagCreateReq.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectIdRes.java
  src/main/java/io/oeid/mogakgo/domain/user/exception/UserException.java
  src/main/java/io/oeid/mogakgo/exception/GlobalExceptionHandler.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode403.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode404.java
  src/main/java/io/oeid/mogakgo/exception/dto/ErrorResponse.java
Labels: ⭐️ Feat, 🎯 MVP1

#18 [CHORE] CI 자동화 구축
  .github/workflows/ci_gradle.yml
Labels: 🧹 Chore

#24 [CHORE] CD 자동화 구축을 위한 Dockerfile 작성
  Dockerfile
Labels: ⭐️ Feat, 🚀 Infra

#25 [CHORE] CD 자동화 구축
  .github/workflows/cd_gradle.yml
Labels: 🧹 Chore, ⭐️ Feat

#58 Refact/#49 notification domain
  src/main/java/io/oeid/mogakgo/domain/notification/domain/Notification.java
  src/main/java/io/oeid/mogakgo/domain/notification/exception/NotificationException.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
Labels: 🔄 Refactor, 🎯 MVP1

#66 [FIX] 오타 수정
  .github/workflows/cd_gradle.yml
Labels: 🎯 MVP1

#71 Fix/#68 project time bug
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/vo/MeetingInfo.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/req/ProjectCreateReq.java
  src/main/java/io/oeid/mogakgo/exception/GlobalExceptionHandler.java
Labels: 🐞 Bug, 🎯 MVP1

#72 Fix/#68 project time bug (#71)
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/vo/MeetingInfo.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/req/ProjectCreateReq.java
  src/main/java/io/oeid/mogakgo/exception/GlobalExceptionHandler.java
Labels: 🐞 Bug, ⭐️ Feat

#67 Refact/#64 user domain
  .gitignore
  src/main/java/io/oeid/mogakgo/domain/auth/oauth/GithubOAuth2UserService.java
  src/main/java/io/oeid/mogakgo/domain/auth/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/AuthController.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/dto/res/AuthAccessTokenResponse.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserCommonService.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserGeoService.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
  src/main/java/io/oeid/mogakgo/domain/user/application/dto/res/UserGeoResponse.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
Labels: 🔄 Refactor, 🎯 MVP1

#74 [FEAT] 프로젝트 카드 동적 쿼리 조회 로직 구현, 커서 기반 페이지네이션 적용
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
Labels: ⭐️ Feat, 🎯 MVP1

#82 Feat/#20 Achievement Domain
  src/main/java/io/oeid/mogakgo/domain/achievement/domain/Achievement.java
  src/main/java/io/oeid/mogakgo/domain/achievement/domain/enums/AchievementType.java
Labels: ⭐️ Feat

#78 [FEAT] GPS-코드 변환 API, 동네 인증 API 개발
  src/main/java/io/oeid/mogakgo/common/swagger/template/CertSwagger.java
  src/main/java/io/oeid/mogakgo/common/swagger/template/GeoSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerCertErrorExamples.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerGeoErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/cert/application/CertService.java
  src/main/java/io/oeid/mogakgo/domain/cert/exception/CertException.java
  src/main/java/io/oeid/mogakgo/domain/cert/presentation/CertController.java
  src/main/java/io/oeid/mogakgo/domain/cert/presentation/dto/req/UserRegionCertAPIReq.java
  src/main/java/io/oeid/mogakgo/domain/cert/presentation/dto/res/UserRegionCertAPIRes.java
  src/main/java/io/oeid/mogakgo/domain/geo/application/GeoService.java
  src/main/java/io/oeid/mogakgo/domain/geo/exception/GeoException.java
  src/main/java/io/oeid/mogakgo/domain/geo/presentation/GeoController.java
  src/main/java/io/oeid/mogakgo/domain/geo/presentation/dto/res/UserRegionInfoAPIRes.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode403.java
Labels: ⭐️ Feat, 🎯 MVP1

#85 FEAT/#51 Pull Notification 생성 구현
  src/main/java/io/oeid/mogakgo/domain/notification/application/NotificationService.java
  src/main/java/io/oeid/mogakgo/domain/notification/application/dto/req/NotificationCreateRequest.java
  src/main/java/io/oeid/mogakgo/domain/notification/application/dto/res/NotificationCreateResponse.java
  src/main/java/io/oeid/mogakgo/domain/notification/domain/Notification.java
Labels: ⭐️ Feat, 🎯 MVP1

#84 [FEAT] 프로젝트 참가 요청 조회 기능 구현
  src/main/java/io/oeid/mogakgo/common/base/CursorPaginationInfoReq.java
  src/main/java/io/oeid/mogakgo/common/base/CursorPaginationResult.java
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerProjectErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/Project.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/ProjectController.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/req/ProjectCreateReq.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/exception/ProjectJoinRequestException.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastruture/ProjectJoinRequestJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastruture/ProjectJoinRequestRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastruture/ProjectJoinRequestRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/projectJoinRequestRes.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserPreviewRes.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode403.java
Labels: ⭐️ Feat, 🎯 MVP1

#83 Feat/#42 User Profile Card를 위한 조회 기능 구현
  src/main/java/io/oeid/mogakgo/common/swagger/template/UserSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerUserErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
  src/main/java/io/oeid/mogakgo/domain/user/application/dto/res/UserProfileResponse.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/req/UserSignUpApiRequest.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserSignUpApiResponse.java
Labels: ⭐️ Feat, 🎯 MVP1

#80 Feat/#19 access token reissue
  src/main/java/io/oeid/mogakgo/common/swagger/template/AuthSwagger.java
  src/main/java/io/oeid/mogakgo/common/swagger/template/OAuth2Swagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerAuthErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/auth/application/AuthService.java
  src/main/java/io/oeid/mogakgo/domain/auth/application/dto/res/AuthReissueResponse.java
  src/main/java/io/oeid/mogakgo/domain/auth/jwt/JwtHelper.java
  src/main/java/io/oeid/mogakgo/domain/auth/jwt/JwtRedisDao.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/AuthController.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/OAuth2Controller.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/dto/res/AuthAccessTokenResponse.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/dto/res/AuthLoginUrlResponse.java
  src/main/java/io/oeid/mogakgo/exception/GlobalExceptionHandler.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode401.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode403.java
Labels: ⭐️ Feat, 🎯 MVP1

#81 [FEAT] ProfileCard와 ProfileCardLike 엔티티 구현
  src/main/java/io/oeid/mogakgo/domain/profile/domain/entity/ProfileCard.java
  src/main/java/io/oeid/mogakgo/domain/profile/domain/entity/ProfileCardLike.java
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
Labels: ⭐️ Feat, 🎯 MVP1

#88 [REFACT] ci, cd 수정
  .github/workflows/cd_gradle.yml
  .github/workflows/ci_gradle.yml
Labels: 🚀 Infra, 🔄 Refactor, 🎯 MVP1

#91 Feat/#90 회원 가입시 유저 조회 기능 추가
  src/main/java/io/oeid/mogakgo/common/swagger/template/UserSwagger.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/req/UserSignUpApiRequest.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserPublicApiResponse.java
Labels: ⭐️ Feat, 🎯 MVP1

#94 Feat/#93 프로젝트 요청 조회 오류 수정
  src/main/java/io/oeid/mogakgo/domain/achievement/domain/enums/AchievementType.java
  src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastruture/ProjectJoinRequestRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/projectJoinRequestRes.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserPublicApiResponse.java
Labels: 🐞 Bug, 🎯 MVP1

#92 [FEAT] 선택한 구역에 대한 프로젝트, 프로필 카드 리스트 랜덤 조회 API, 프로젝트 매칭 요청 생성 API 개발
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProfileCardSwagger.java
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectJoinRequestSwagger.java
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerProjectJoinRequestErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/cert/application/CertService.java
  src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardService.java
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/profile/presentation/ProfileCardController.java
  src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/ProjectController.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/MeetingInfoResponse.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDetailAPIRes.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/application/dto/req/ProjectJoinCreateReq.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/domain/entity/ProjectJoinRequest.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/ProjectJoinRequestController.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/dto/res/ProjectJoinRequestAPIRes.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserPublicApiResponse.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode403.java
Labels: ⭐️ Feat, 🎯 MVP1

#101 Feat/#34 프로젝트 요청 수락 겸 매칭 성사 기능 구현
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectJoinReqSwagger.java
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerProjectErrorExamples.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerProjectJoinReqErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/matching/application/MatchingService.java
  src/main/java/io/oeid/mogakgo/domain/matching/application/UserMatchingService.java
  src/main/java/io/oeid/mogakgo/domain/matching/domain/entity/Matching.java
  src/main/java/io/oeid/mogakgo/domain/matching/domain/entity/enums/MatchingStatus.java
  src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/matching/presentation/dto/res/MatchingId.java
  src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/Project.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/enums/ProjectStatus.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/ProjectController.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/domain/entity/ProjectJoinRequest.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/domain/entity/enums/RequestStatus.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/ProjectJoinRequestController.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/dto/res/ProjectJoinReqId.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/dto/res/projectJoinRequestRes.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode404.java
Labels: ⭐️ Feat, 🔄 Refactor, 🎯 MVP1

#100 [FEAT] 이미 매칭을 보낸 사용자의 추가 매칭 불가를 검사하는 유효성 검사 기능 개발
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectJoinReqSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerProjectJoinRequestErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestJpaRepository.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
Labels: ⭐️ Feat, 🎯 MVP1

#98 [FEAT] 사용자가 보낸 프로젝트 매칭 요청 리스트 조회 API 개발
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectJoinReqSwagger.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/ProjectJoinRequestController.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/dto/res/ProjectJoinRequestDetailAPIRes.java
Labels: ⭐️ Feat, 🎯 MVP1

#105 Bug/#103 OAuth2 로그인 응답 반환
  src/main/java/io/oeid/mogakgo/common/swagger/template/OAuth2Swagger.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/OAuth2Controller.java
Labels: 🐞 Bug, 🎯 MVP1

#106 [FEAT] 매칭 취소 기능 개발
  src/main/java/io/oeid/mogakgo/common/swagger/template/MatchingSwagger.java
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectJoinReqSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerMatchingErrorExamples.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerProjectErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/matching/application/MatchingService.java
  src/main/java/io/oeid/mogakgo/domain/matching/domain/entity/Matching.java
  src/main/java/io/oeid/mogakgo/domain/matching/domain/entity/enums/MatchingStatus.java
  src/main/java/io/oeid/mogakgo/domain/matching/exception/MatchingException.java
  src/main/java/io/oeid/mogakgo/domain/matching/presentation/MatchingController.java
  src/main/java/io/oeid/mogakgo/domain/matching/presentation/dto/MatchingId.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/Project.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/enums/ProjectStatus.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/ProjectJoinRequestController.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode403.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode404.java
Labels: ⭐️ Feat, 🎯 MVP1

#107 [FEAT] 지역별 프로젝트 밀집도 랭크 조회 기능
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectSwagger.java
  src/main/java/io/oeid/mogakgo/domain/geo/domain/enums/Region.java
  src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/ProjectController.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDensityRankRes.java
Labels: ⭐️ Feat, 🎯 MVP1

#109 [Bug] 프로젝트, 프로필 카드 랜덤 리스트 조회 API 동작 오류 해결, 불변 리스트 정렬 불가 오류 해결
  src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardService.java
  src/main/java/io/oeid/mogakgo/domain/profile/domain/entity/ProfileCard.java
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
Labels: 🐞 Bug, 🎯 MVP1

#113 Feat/#50 Pull Notification Pagination 적용
  src/main/java/io/oeid/mogakgo/common/swagger/template/NotificationSwagger.java
  src/main/java/io/oeid/mogakgo/domain/auth/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/io/oeid/mogakgo/domain/notification/application/NotificationService.java
  src/main/java/io/oeid/mogakgo/domain/notification/application/dto/req/NotificationCreateRequest.java
  src/main/java/io/oeid/mogakgo/domain/notification/application/dto/res/NotificationCreateResponse.java
  src/main/java/io/oeid/mogakgo/domain/notification/domain/Notification.java
  src/main/java/io/oeid/mogakgo/domain/notification/infrastructure/NotificationCustomRepository.java
  src/main/java/io/oeid/mogakgo/domain/notification/infrastructure/NotificationCustomRepositoryImpl.java
  src/main/java/io/oeid/mogakgo/domain/notification/infrastructure/NotificationJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/notification/presentation/NotificationController.java
  src/main/java/io/oeid/mogakgo/domain/notification/presentation/dto/res/NotificationPublicApiRes.java
  src/main/java/io/oeid/mogakgo/domain/notification/presentation/vo/NotificationDataVo.java
  src/main/java/io/oeid/mogakgo/domain/notification/presentation/vo/NotificationSenderVo.java
Labels: ⭐️ Feat, 🎯 MVP1

#120 [REFACT] 프로젝트 생성자에 대해 해당 프로젝트에 대한 매칭 요청 불가 에러코드 변경 (403 -> 400)
  src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
Labels: 🔄 Refactor, 🎯 MVP1

#121 Bug/#116 매핑 테이블 중복 로직 수정
  src/main/java/io/oeid/mogakgo/common/swagger/template/UserSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerUserErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
Labels: 🐞 Bug, 🎯 MVP1

#123 [FIX] 프로젝트 취소 시 요청들 모두 취소하기 구현
  src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestJpaRepository.java
Labels: 🐞 Bug, 🎯 MVP1

#122 [FIX] 매칭 생성 시 해당 프로젝트 다른 요청들 거절하는 로직 구현
  src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestJpaRepository.java
Labels: 🐞 Bug, 🎯 MVP1

#127 [BUG] 프로젝트, 프로필 카드 리스트 조회할 때, 업적 조회 시 발생하는 NPE 해결
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
Labels: 🐞 Bug

#132 [REFACT] 프로젝트 생성일 유효성 검사, 프로젝트 상태 유효성 검사, 프로젝트 상태 필드 추가
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/dto/res/ProjectJoinRequestDetailAPIRes.java
Labels: 🔄 Refactor, 🎯 MVP1

#131 [FIX] Api 오류들 수정
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectJoinReqSwagger.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/dto/res/ProjectJoinRequestDetailAPIRes.java
Labels: 🐞 Bug, 🎯 MVP1

#154 Bug/#140 Refresh Token 쿠키 확인 불가
  src/main/java/io/oeid/mogakgo/common/swagger/template/AuthSwagger.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/AuthController.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/OAuth2Controller.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/dto/req/AuthReissueRequest.java
Labels: 🐞 Bug, 🎯 MVP1

#134 [FEAT] sql문 실행으로 스케쥴러 구현
  src/main/java/io/oeid/mogakgo/core/configuration/SchedulerConfig.java
  src/main/java/io/oeid/mogakgo/scheduler/FinishedProjectScheduler.java
  src/main/resources/sql/finished_matched_project_after_12.sql
  src/main/resources/sql/finished_pending_project_after_12.sql
  src/main/resources/sql/rejected_project_request_about_finished_project.sql
Labels: ⭐️ Feat, 🎯 MVP1

#159 [REFACT] 프로필 카드 리스트 조회 시, 탈퇴한 사용자에 대한 필터링 로직 추가
  src/main/java/io/oeid/mogakgo/domain/cert/application/CertService.java
  src/main/java/io/oeid/mogakgo/domain/geo/application/GeoService.java
  src/main/java/io/oeid/mogakgo/domain/geo/application/feign/KakaoFeignClient.java
  src/main/java/io/oeid/mogakgo/domain/geo/application/feign/dto/AddressDocument.java
  src/main/java/io/oeid/mogakgo/domain/geo/application/feign/dto/AddressInfoDto.java
  src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardService.java
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode401.java
Labels: 🔄 Refactor, 🎯 MVP1

#164 [CHORE] websocket, mongoDB 의존 추가
  build.gradle
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/AuthController.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/dto/req/AuthReissueRequest.java
Labels: 🧹 Chore, 🎯 MVP1

#166 [REFACT] 전반적인 API 리팩토링, 프로필 카드에 대한 찔러보기 요청 취소 API 기능 개발
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProfileCardLikeSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerProfileCardErrorExamples.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerProfileCardLikeErrorExamples.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerUserErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/cert/application/CertService.java
  src/main/java/io/oeid/mogakgo/domain/geo/application/GeoService.java
  src/main/java/io/oeid/mogakgo/domain/geo/domain/enums/Region.java
  src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardLikeService.java
  src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardService.java
  src/main/java/io/oeid/mogakgo/domain/profile/application/dto/req/UserProfileCardReq.java
  src/main/java/io/oeid/mogakgo/domain/profile/domain/entity/ProfileCard.java
  src/main/java/io/oeid/mogakgo/domain/profile/domain/entity/ProfileCardLike.java
  src/main/java/io/oeid/mogakgo/domain/profile/exception/ProfileCardException.java
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardLikeJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardLikeRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardLikeRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/profile/presentation/ProfileCardLikeController.java
  src/main/java/io/oeid/mogakgo/domain/profile/presentation/dto/req/UserProfileLikeCancelAPIReq.java
  src/main/java/io/oeid/mogakgo/domain/profile/presentation/dto/req/UserProfileLikeCreateAPIReq.java
  src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/Project.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/domain/entity/ProjectJoinRequest.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode404.java
Labels: 🔄 Refactor, 🎯 MVP1

#169 [FIX] sql문 상태 이름 오류 수정
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectJpaRepository.java
Labels: 🐞 Bug, 🎯 MVP1

#170 [FIX] sql문 상태 이름 오류 수정 (#169)
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectJpaRepository.java
Labels: 🐞 Bug, 🎯 MVP1

#174 [REFACT] 프로젝트 카드 랜덤 리스트 조회 API에서 프로젝트 상태 필드를 추가로 전달하도록 수정, queryDSL warn 해결
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDetailAPIRes.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/dto/res/ProjectJoinRequestDetailAPIRes.java
Labels: 🔄 Refactor, 🎯 MVP1

#175 Feat/#148 user update
  src/main/java/io/oeid/mogakgo/common/swagger/template/UserSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerUserErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/AchievementJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/notification/presentation/dto/req/FCMTokenApiRequest.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
  src/main/java/io/oeid/mogakgo/domain/user/application/dto/req/UserUpdateReq.java
  src/main/java/io/oeid/mogakgo/domain/user/application/dto/res/UserUpdateRes.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/req/UserSignUpApiReq.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/req/UserUpdateApiReq.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserSignUpApiResponse.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserUpdateApiRes.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
Labels: ⭐️ Feat, 🎯 MVP1

#171 Feat/#145, 146 websocket chat
  src/main/java/io/oeid/mogakgo/common/swagger/template/ChatSwagger.java
  src/main/java/io/oeid/mogakgo/core/configuration/WebSocketConfig.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerChatErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/ChatService.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/ChatWebSocketService.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/dto/req/ChatRoomCreateReq.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/dto/res/ChatRoomCreateRes.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/dto/res/ChatRoomDataRes.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/dto/res/ChatRoomPublicRes.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/vo/ChatData.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/vo/ChatRoomProjectInfo.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/vo/ChatUserInfo.java
  src/main/java/io/oeid/mogakgo/domain/chat/entity/document/ChatMessage.java
  src/main/java/io/oeid/mogakgo/domain/chat/entity/document/ChatRoom.java
  src/main/java/io/oeid/mogakgo/domain/chat/entity/enums/ChatMessageType.java
  src/main/java/io/oeid/mogakgo/domain/chat/entity/enums/ChatStatus.java
  src/main/java/io/oeid/mogakgo/domain/chat/exception/ChatException.java
  src/main/java/io/oeid/mogakgo/domain/chat/handler/CustomWebSocketHandler.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRepository.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRoomCustomRepository.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRoomCustomRepositoryImpl.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRoomRoomJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRoomSessionRepository.java
  src/main/java/io/oeid/mogakgo/domain/chat/presentation/ChatController.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode404.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode500.java
Labels: 🧹 Chore, ⭐️ Feat, 🎯 MVP1

#177 [FEAT] 현재 회원 매칭 상태 확인하는 기능 구현
  src/main/java/io/oeid/mogakgo/common/swagger/template/UserSwagger.java
  src/main/java/io/oeid/mogakgo/domain/matching/presentation/MatchingController.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserMatchingStatus.java
Labels: ⭐️ Feat, 🎯 MVP1

#176 Feat/#135 내 매칭 기록 조회하기
  src/main/java/io/oeid/mogakgo/common/base/CursorPaginationInfoReq.java
  src/main/java/io/oeid/mogakgo/common/swagger/template/MatchingSwagger.java
  src/main/java/io/oeid/mogakgo/domain/matching/application/MatchingService.java
  src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/matching/presentation/MatchingController.java
  src/main/java/io/oeid/mogakgo/domain/matching/presentation/dto/MatchingHistoryRes.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustomImpl.java
Labels: 🐞 Bug, ⭐️ Feat, 🎯 MVP1

#179 [MERGE] dev 를 main 에 병합
  src/main/java/io/oeid/mogakgo/common/base/CursorPaginationInfoReq.java
  src/main/java/io/oeid/mogakgo/common/swagger/template/ChatSwagger.java
  src/main/java/io/oeid/mogakgo/common/swagger/template/MatchingSwagger.java
  src/main/java/io/oeid/mogakgo/common/swagger/template/UserSwagger.java
  src/main/java/io/oeid/mogakgo/core/configuration/WebSocketConfig.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerChatErrorExamples.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerUserErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/AchievementJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/ChatService.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/ChatWebSocketService.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/dto/req/ChatRoomCreateReq.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/dto/res/ChatRoomCreateRes.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/dto/res/ChatRoomDataRes.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/dto/res/ChatRoomPublicRes.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/vo/ChatData.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/vo/ChatRoomProjectInfo.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/vo/ChatUserInfo.java
  src/main/java/io/oeid/mogakgo/domain/chat/entity/document/ChatMessage.java
  src/main/java/io/oeid/mogakgo/domain/chat/entity/document/ChatRoom.java
  src/main/java/io/oeid/mogakgo/domain/chat/entity/enums/ChatMessageType.java
  src/main/java/io/oeid/mogakgo/domain/chat/entity/enums/ChatStatus.java
  src/main/java/io/oeid/mogakgo/domain/chat/exception/ChatException.java
  src/main/java/io/oeid/mogakgo/domain/chat/handler/CustomWebSocketHandler.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRepository.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRoomCustomRepository.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRoomCustomRepositoryImpl.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRoomRoomJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRoomSessionRepository.java
  src/main/java/io/oeid/mogakgo/domain/chat/presentation/ChatController.java
  src/main/java/io/oeid/mogakgo/domain/matching/application/MatchingService.java
  src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/matching/presentation/MatchingController.java
  src/main/java/io/oeid/mogakgo/domain/matching/presentation/dto/MatchingHistoryRes.java
  src/main/java/io/oeid/mogakgo/domain/notification/presentation/dto/req/FCMTokenApiRequest.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDetailAPIRes.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/dto/res/ProjectJoinRequestDetailAPIRes.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
  src/main/java/io/oeid/mogakgo/domain/user/application/dto/req/UserUpdateReq.java
  src/main/java/io/oeid/mogakgo/domain/user/application/dto/res/UserUpdateRes.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/req/UserSignUpApiReq.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/req/UserUpdateApiReq.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserMatchingStatus.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserSignUpApiResponse.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserUpdateApiRes.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode404.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode500.java
Labels: ⭐️ Feat, 🎯 MVP1

#185 Bug/#184 Reissue Authroization
  src/main/java/io/oeid/mogakgo/core/configuration/SecurityConfig.java
Labels: 🐞 Bug, 🎯 MVP1

#188 Bug/#187 chatroom 조회 오류 수정
  src/main/java/io/oeid/mogakgo/domain/chat/application/dto/res/ChatRoomPublicRes.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRoomCustomRepositoryImpl.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
Labels: 🐞 Bug, 🎯 MVP1

#192 Refact/#191 채팅방 API 분리
  src/main/java/io/oeid/mogakgo/common/swagger/template/ChatSwagger.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/ChatIdSequenceGeneratorService.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/ChatService.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/ChatWebSocketService.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/dto/res/ChatDataRes.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/dto/res/ChatRoomCreateRes.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/dto/res/ChatRoomDataRes.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/vo/ChatRoomProjectInfo.java
  src/main/java/io/oeid/mogakgo/domain/chat/entity/ChatRoom.java
  src/main/java/io/oeid/mogakgo/domain/chat/entity/document/ChatIdSequence.java
  src/main/java/io/oeid/mogakgo/domain/chat/entity/document/ChatMessage.java
  src/main/java/io/oeid/mogakgo/domain/chat/handler/CustomWebSocketHandler.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRepository.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRoomCustomRepositoryImpl.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRoomRoomJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/chat/presentation/ChatController.java
Labels: ⭐️ Feat, 🎯 MVP1

#189 Feat/#182 업적 도메인 구현
  src/main/java/io/oeid/mogakgo/domain/achievement/domain/entity/Achievement.java
  src/main/java/io/oeid/mogakgo/domain/achievement/domain/entity/UserAchievement.java
  src/main/java/io/oeid/mogakgo/domain/achievement/domain/entity/UserActivity.java
  src/main/java/io/oeid/mogakgo/domain/achievement/domain/entity/enums/ActivityType.java
  src/main/java/io/oeid/mogakgo/domain/achievement/domain/entity/enums/RequirementType.java
  src/main/java/io/oeid/mogakgo/domain/achievement/domain/enums/AchievementType.java
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/AchievementJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
Labels: ⭐️ Feat, 🎯 MVP1

#190 Feat/#141 리뷰 추가 기능 구현
  src/main/java/io/oeid/mogakgo/domain/project/domain/entity/Project.java
  src/main/java/io/oeid/mogakgo/domain/review/application/ReviewService.java
  src/main/java/io/oeid/mogakgo/domain/review/application/dto/req/ReviewCreateReq.java
  src/main/java/io/oeid/mogakgo/domain/review/application/dto/res/ReviewCreateRes.java
  src/main/java/io/oeid/mogakgo/domain/review/domain/Review.java
  src/main/java/io/oeid/mogakgo/domain/review/domain/enums/ReviewRating.java
  src/main/java/io/oeid/mogakgo/domain/review/exception/ReviewException.java
  src/main/java/io/oeid/mogakgo/domain/review/infrastructure/ReviewJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
Labels: ⭐️ Feat, 🎯 MVP1

#181 Feat/#142 jandi rate
  src/main/java/io/oeid/mogakgo/common/swagger/template/UserSwagger.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
  src/main/java/io/oeid/mogakgo/domain/user/application/dto/res/UserJandiRateRes.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
Labels: ⭐️ Feat, 🎯 MVP1

#183 [FEAT] 사용자가 생성한 프로젝트, 프로젝트 리스트 조회 API 개발
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectSwagger.java
  src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/ProjectController.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDetailAPIRes.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectInfoAPIRes.java
Labels: ⭐️ Feat, 🎯 MVP1
