Repository Open-Eye-Im-Developer/MoGakGo-BE, pull requests merged in 2024-03, with the labels that each got.

#197 [FEAT] 채팅방 나가기 API 기능 개발
  src/main/java/io/oeid/mogakgo/common/swagger/template/ChatSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerChatErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/ChatService.java
  src/main/java/io/oeid/mogakgo/domain/chat/entity/ChatRoom.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRoomCustomRepositoryImpl.java
  src/main/java/io/oeid/mogakgo/domain/chat/presentation/ChatController.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
Labels: ⭐️ Feat, 🎯 MVP1

#196 [FEAT] 사용자의 대표 업적 변경 API 기능 개발
  src/main/java/io/oeid/mogakgo/common/swagger/template/UserSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerAchievementErrorExamples.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerUserAchievementErrorExamples.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerUserErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/achievement/domain/entity/UserAchievement.java
  src/main/java/io/oeid/mogakgo/domain/achievement/exception/AchievementException.java
  src/main/java/io/oeid/mogakgo/domain/achievement/exception/UserAchievementException.java
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
  src/main/java/io/oeid/mogakgo/domain/user/application/dto/res/UserUpdateRes.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/req/UserAchievementUpdateApiRequest.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserAchievementUpdateApiResponse.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserUpdateApiRes.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode403.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode404.java
Labels: ⭐️ Feat, 🎯 MVP1

#200 [REFACT] 프로젝트, 프로필 카드 리스트 정렬 시, 마지막 원소를 제외하고 랜덤 정렬하도록 수정
  src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardService.java
  src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
Labels: 🔄 Refactor, 🎯 MVP1

#205 [FEAT] 데이터베이스 스키마에 대한 형상 관리를 위한 Flyway 적용
  build.gradle
  src/main/resources/db/migration/V1__init.sql
Labels: 🚀 Infra, 🎯 MVP1

#201 Feat/#198 review api
  src/main/java/io/oeid/mogakgo/common/swagger/template/ReviewSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerReviewErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/review/application/ReviewService.java
  src/main/java/io/oeid/mogakgo/domain/review/application/dto/req/ReviewCreateReq.java
  src/main/java/io/oeid/mogakgo/domain/review/application/dto/res/ReviewCreateRes.java
  src/main/java/io/oeid/mogakgo/domain/review/domain/enums/ReviewRating.java
  src/main/java/io/oeid/mogakgo/domain/review/presentation/ReviewController.java
  src/main/java/io/oeid/mogakgo/domain/review/presentation/dto/req/ReviewCreateApiReq.java
  src/main/java/io/oeid/mogakgo/domain/review/presentation/dto/res/ReviewCreateApiRes.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
Labels: ⭐️ Feat, 🎯 MVP1

#202 Feat/#151 notification check
  src/main/java/io/oeid/mogakgo/common/swagger/template/NotificationSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerNotificationErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/notification/application/NotificationService.java
  src/main/java/io/oeid/mogakgo/domain/notification/application/dto/res/NotificationCheckedRes.java
  src/main/java/io/oeid/mogakgo/domain/notification/domain/Notification.java
  src/main/java/io/oeid/mogakgo/domain/notification/infrastructure/NotificationJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/notification/presentation/NotificationController.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode404.java
Labels: ⭐️ Feat, 🎯 MVP1

#204 [FEAT] 테스트용 유저 인증 어노테이션 구현
  src/main/java/io/oeid/mogakgo/core/properties/JwtProperties.java
  src/test/java/io/oeid/mogakgo/core/support/WithMockCustomUser.java
  src/test/java/io/oeid/mogakgo/core/support/WithMockCustomUserSecurityContextFactory.java
Labels: ⭐️ Feat, 🧪 TEST, 🎯 MVP1

#210 [BUG] 프로젝트, 프로필 카드 리스트 랜덤 정렬 시, 2개 이하의 리스트에 대해 발생하는 예외 처리
  src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardService.java
  src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
Labels: 🐞 Bug

#213 [BUG] 초기 데이터베이스 스키마 flyway 적용에서 sql 컬럼명 오타 수정
  src/main/resources/db/migration/V1__init.sql
Labels: 🐞 Bug

#220 [REFACT] 사용자의 '찔러보기' 요청 제약조건 제거 관련 리팩토링
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProfileCardLikeSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerUserErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
Labels: 🔄 Refactor, 🎯 MVP1

#222 Test/#221 user domain
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/UserDevelopLanguageTag.java
  src/test/java/io/oeid/mogakgo/domain/user/domain/UserDevelopLanguageTagDomainTest.java
  src/test/java/io/oeid/mogakgo/domain/user/domain/UserDomainTest.java
  src/test/java/io/oeid/mogakgo/domain/user/domain/UserWantedJobTagDomainTest.java
Labels: 🧪 TEST, 🎯MVP2

#215 Refact/#209 review enum
  src/main/java/io/oeid/mogakgo/domain/review/domain/enums/ReviewRating.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
Labels: 🔄 Refactor, 🎯MVP2

#223 [FEAT] 사용자의 진행중 · 달성 업적 상세 조회, 사용자의 미달성 업적 상세 조회 API 개발
  src/main/java/io/oeid/mogakgo/common/swagger/template/AchievementSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerUserAchievementErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementService.java
  src/main/java/io/oeid/mogakgo/domain/achievement/application/dto/res/AchievementInfoRes.java
  src/main/java/io/oeid/mogakgo/domain/achievement/application/dto/res/UserAchievementInfoRes.java
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/achievement/presentation/AchievementController.java
  src/main/java/io/oeid/mogakgo/domain/achievement/presentation/dto/res/NonAchievedDetailAPIRes.java
  src/main/java/io/oeid/mogakgo/domain/achievement/presentation/dto/res/UserAchievementDetailAPIRes.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode403.java
Labels: ⭐️ Feat, 🎯 MVP1

#226 Test/#225 user service
  src/main/java/io/oeid/mogakgo/domain/user/application/UserAchievementService.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserGeoService.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserProfileService.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
  src/main/java/io/oeid/mogakgo/domain/user/application/dto/req/UserUpdateReq.java
  src/main/java/io/oeid/mogakgo/domain/user/application/dto/res/UserGeoResponse.java
  src/main/java/io/oeid/mogakgo/domain/user/application/dto/res/UserProfileResponse.java
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/req/UserUpdateApiReq.java
  src/test/java/io/oeid/mogakgo/domain/user/application/UserCommonServiceTest.java
  src/test/java/io/oeid/mogakgo/domain/user/application/UserServiceTest.java
Labels: 🧪 TEST, 🎯MVP2

#227 [REFACT] 선택한 구역에 대한 프로필 카드 리스트 조회 API 리팩토링
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProfileCardSwagger.java
  src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardService.java
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/profile/presentation/ProfileCardController.java
  src/main/java/io/oeid/mogakgo/domain/profile/presentation/dto/res/UserProfileInfoAPIRes.java
Labels: 🔄 Refactor, 🎯MVP2

#230 Test/#229 jwt token
  src/main/java/io/oeid/mogakgo/domain/auth/jwt/JwtHelper.java
  src/test/java/io/oeid/mogakgo/domain/auth/jwt/JwtHelperTest.java
Labels: 🧪 TEST, 🎯MVP2

#239 [REFACT] 사용자의 업적 상세 조회 API를 하나로 합침, 업적 상세 조회 로직 구현
  src/main/java/io/oeid/mogakgo/common/swagger/template/AchievementSwagger.java
  src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementService.java
  src/main/java/io/oeid/mogakgo/domain/achievement/application/dto/res/AchievementInfoRes.java
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/achievement/presentation/AchievementController.java
  src/main/java/io/oeid/mogakgo/domain/achievement/presentation/dto/res/NonAchievedDetailAPIRes.java
  src/main/java/io/oeid/mogakgo/domain/achievement/presentation/dto/res/UserAchievementDetailAPIRes.java
Labels: 🔄 Refactor, 🎯MVP2

#233 [REFACT] 유저 프로필 조회 업적 ID 추가
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDetailAPIRes.java
  src/main/java/io/oeid/mogakgo/domain/user/application/dto/res/UserProfileResponse.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserPublicApiResponse.java
Labels: 🔄 Refactor, 🎯MVP2

#235 [BUG] 채팅방 상세 정보 조회 수정
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRoomCustomRepositoryImpl.java
Labels: 🐞 Bug, 🎯 MVP1

#237 Refact/#236 notification domain
  src/main/java/io/oeid/mogakgo/domain/notification/application/NotificationService.java
  src/main/java/io/oeid/mogakgo/domain/notification/application/dto/req/NotificationCreateRequest.java
  src/main/java/io/oeid/mogakgo/domain/notification/application/dto/res/NotificationCreateResponse.java
  src/main/java/io/oeid/mogakgo/domain/notification/domain/Notification.java
  src/main/java/io/oeid/mogakgo/domain/notification/infrastructure/NotificationCustomRepository.java
  src/main/java/io/oeid/mogakgo/domain/notification/infrastructure/NotificationCustomRepositoryImpl.java
  src/main/java/io/oeid/mogakgo/domain/notification/presentation/dto/res/NotificationPublicApiRes.java
  src/main/java/io/oeid/mogakgo/domain/notification/presentation/vo/NotificationDataVo.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
  src/main/resources/db/migration/V3__notification_refactor.sql
Labels: 🔄 Refactor, 🎯MVP2

#240 Feat/#149 chat fcm push
  src/main/java/io/oeid/mogakgo/common/swagger/template/ChatSwagger.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/ChatService.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/ChatWebSocketService.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/dto/req/ChatReq.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/dto/res/ChatDataRes.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRepository.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatUserJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/chat/presentation/ChatController.java
  src/main/java/io/oeid/mogakgo/domain/chat/presentation/ChatWebSocketController.java
  src/main/java/io/oeid/mogakgo/domain/chat/presentation/dto/req/ChatApiReq.java
  src/main/java/io/oeid/mogakgo/domain/chat/presentation/dto/res/ChatDataApiRes.java
  src/main/java/io/oeid/mogakgo/domain/notification/application/FCMNotificationService.java
Labels: ⭐️ Feat, 🎯 MVP1

#243 [REFACT] API 엔드포인트 수정
  src/main/java/io/oeid/mogakgo/domain/achievement/presentation/AchievementController.java
Labels: 🔄 Refactor, 🎯MVP2

#247 [REFACT] 프로젝트 매칭 히스토리 조회 시, 매칭 상태 필터링 추가
  src/main/java/io/oeid/mogakgo/common/swagger/template/MatchingSwagger.java
  src/main/java/io/oeid/mogakgo/domain/matching/application/MatchingService.java
  src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/matching/presentation/MatchingController.java
Labels: 🔄 Refactor, 🎯MVP2

#248 [FEAT] 사용자가 생성한 최신 프로젝트 상세 조회 API 개발
  src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectSwagger.java
  src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/ProjectController.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDetailInfoAPIRes.java
Labels: ⭐️ Feat, 🎯MVP2

#253 [REFACT] 사용자의 프로젝트 조회 API 리팩토링
  src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/ProjectController.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDetailInfoAPIRes.java
Labels: 🔄 Refactor, 🎯MVP2

#256 [BUG] 사용자의 프로젝트 요청 리스트 조회 시, 페이지네이션이 제대로 작동하지 않아요!
  src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/dto/res/ProjectJoinRequestDetailAPIRes.java
Labels: 🐞 Bug

#259 [REFACT] 사용자의 '찔러보기' 요청 리스트 조회 API 리팩토링
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardLikeRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/profile/presentation/dto/res/UserProfileLikeInfoAPIRes.java
Labels: 🔄 Refactor, 🎯MVP2

#265 [BUG] 사용자의 업적 상세 조회가 제대로 작동하지 않아요!
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementRepositoryCustomImpl.java
Labels: 🐞 Bug

#262 Refact/#261 UserGithubUtil 리펙토링
  src/main/java/io/oeid/mogakgo/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
  src/main/java/io/oeid/mogakgo/domain/user/util/UserGithubUtil.java
Labels: 🔄 Refactor, 🎯MVP2

#268 Refact/#267 user develop language modify
  src/main/java/io/oeid/mogakgo/domain/user/domain/enums/DevelopLanguage.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserDevelopLanguageApiRes.java
Labels: 🔄 Refactor, 🎯MVP2

#271 Refact/#269 oauth2 login
  build.gradle
  src/main/java/io/oeid/mogakgo/common/swagger/template/AuthSwagger.java
  src/main/java/io/oeid/mogakgo/common/swagger/template/OAuth2Swagger.java
  src/main/java/io/oeid/mogakgo/core/configuration/SecurityConfig.java
  src/main/java/io/oeid/mogakgo/domain/auth/application/AuthService.java
  src/main/java/io/oeid/mogakgo/domain/auth/application/AuthUserService.java
  src/main/java/io/oeid/mogakgo/domain/auth/application/dto/res/AuthLoginResponse.java
  src/main/java/io/oeid/mogakgo/domain/auth/application/dto/res/AuthOAuth2Response.java
  src/main/java/io/oeid/mogakgo/domain/auth/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/AuthController.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/OAuth2Controller.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/dto/req/AuthReissueApiRequest.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/dto/res/AuthAccessTokenApiResponse.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/dto/res/AuthLoginUrlResponse.java
  src/main/java/io/oeid/mogakgo/domain/auth/util/GithubOAuth2Manager.java
Labels: 🔄 Refactor, 🎯MVP2

#272 Refact/#270 user info
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDetailAPIRes.java
  src/main/java/io/oeid/mogakgo/domain/user/application/dto/res/UserProfileResponse.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserPublicApiResponse.java
  src/test/java/io/oeid/mogakgo/domain/user/application/UserServiceTest.java
Labels: 🔄 Refactor, 🎯MVP2

#275 Refact/#274 reissue
  src/main/java/io/oeid/mogakgo/common/swagger/template/AuthSwagger.java
  src/main/java/io/oeid/mogakgo/domain/auth/presentation/AuthController.java
Labels: 🔄 Refactor, 🎯MVP2

#277 Feat/#276 chat room
  src/main/java/io/oeid/mogakgo/common/swagger/template/ChatSwagger.java
  src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerChatErrorExamples.java
  src/main/java/io/oeid/mogakgo/domain/chat/application/ChatService.java
  src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRoomRoomJpaRepository.java
  src/main/java/io/oeid/mogakgo/domain/chat/presentation/ChatController.java
  src/main/java/io/oeid/mogakgo/domain/chat/presentation/dto/res/ChatRoomIdApiRes.java
Labels: ⭐️ Feat, 🎯MVP2

#281 [BUG] 업적 이력 이벤트 발행과 재시도 처리가 제대로 작동하지 않아요!
  src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementEventService.java
Labels: 🐞 Bug

#283 [FEAT] 현재 매칭 된 프로젝트 정보 가져오기 기능
  src/main/java/io/oeid/mogakgo/common/swagger/template/MatchingSwagger.java
  src/main/java/io/oeid/mogakgo/domain/matching/application/MatchingService.java
  src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustom.java
  src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/matching/presentation/MatchingController.java
  src/main/java/io/oeid/mogakgo/domain/matching/presentation/dto/MatchingProjectRes.java
  src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDetailAPIRes.java
Labels: ⭐️ Feat

#293 Feat/#292 매칭 요청시 PULL 알림 전달 기능 추가
  src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
Labels: ⭐️ Feat, 🎯MVP2

#297 [REFACT] 현재 매칭 된 프로젝트 정보 가져오기 기능 스키마 수정 (#296)
  src/main/java/io/oeid/mogakgo/domain/matching/presentation/dto/MatchingProjectRes.java
  src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
Labels: 🔄 Refactor

#304 [REFACT] 소켓 연결 후 세션 처리 로직 리팩토링 및 progressCount NPE 해결
  src/main/java/io/oeid/mogakgo/common/event/handler/AchievementEventHandler.java
  src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementSocketService.java
  src/main/java/io/oeid/mogakgo/domain/achievement/domain/entity/vo/UserId.java
  src/main/java/io/oeid/mogakgo/domain/achievement/handler/AchievementSocketHandler.java
Labels: 🔄 Refactor, 🎯MVP2

#300 Feat/#291 project finished notification
  src/main/java/io/oeid/mogakgo/domain/notification/application/FCMNotificationService.java
  src/main/java/io/oeid/mogakgo/domain/notification/application/NotificationService.java
  src/main/java/io/oeid/mogakgo/domain/notification/domain/enums/NotificationMessage.java
  src/main/java/io/oeid/mogakgo/scheduler/FinishedProjectScheduler.java
Labels: ⭐️ Feat, 🎯MVP2

#307 [REFACT] session 저장 로직 수정 및 로그 추가
  src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementSocketService.java
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/session/AchievementSessionRepository.java
Labels: 🔄 Refactor

#310 [REFACT] 업적 관련 소켓 통신 시, 응답 타입 DTO 수정
  src/main/java/io/oeid/mogakgo/common/event/handler/AchievementEventHandler.java
  src/main/java/io/oeid/mogakgo/domain/achievement/domain/entity/AchievementMessage.java
Labels: 🔄 Refactor, 🎯MVP2

#311 FEAT/#295 달성 업적에 대한 PULL 알림 기능 추가
  src/main/java/io/oeid/mogakgo/common/event/handler/AchievementEventHandler.java
Labels: ⭐️ Feat, 🎯MVP2

#314 [FEAT] 특정 업적 상세 정보 조회 API 개발
  src/main/java/io/oeid/mogakgo/common/swagger/template/AchievementSwagger.java
  src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementService.java
  src/main/java/io/oeid/mogakgo/domain/achievement/presentation/AchievementController.java
  src/main/java/io/oeid/mogakgo/domain/achievement/presentation/dto/res/AchievementInfoAPIRes.java
Labels: ⭐️ Feat, 🎯MVP2

#320 [FEAT] 업적 이벤트에 STOMP 적용
  src/main/java/io/oeid/mogakgo/common/event/handler/AchievementEventHandler.java
  src/main/java/io/oeid/mogakgo/core/configuration/WebSocketConfig.java
  src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementSocketService.java
  src/main/java/io/oeid/mogakgo/domain/achievement/handler/AchievementSocketHandler.java
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/session/AchievementSessionRepository.java
  src/main/java/io/oeid/mogakgo/domain/chat/interceptor/StompInterceptor.java
Labels: 🔄 Refactor, 🎯MVP2

#323 [FEAT] 사용자의 업적 달성 여부 검종 메서드 수정
  src/main/java/io/oeid/mogakgo/common/event/handler/AchievementEventHandler.java
Labels: 🐞 Bug

#326 [REFACT] 업적 이력 메시지 전송을 위한 검증 로직 오류 수정
  src/main/java/io/oeid/mogakgo/common/event/handler/AchievementEventHandler.java
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/AchievementJpaRepository.java
Labels: 🔄 Refactor, 🎯MVP2

#329 [REFACT] 누적 업적에 대한 progressCount 조회 로직 수정, 업적 달성을 위한 검증 로직 리팩토링
  src/main/java/io/oeid/mogakgo/common/aop/AchievementEventAspect.java
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustomImpl.java
Labels: 🔄 Refactor, 🎯MVP2

#332 [REFACT] 사용자의 대표 업적 변경 API 수정
  src/main/java/io/oeid/mogakgo/common/aop/AchievementEventAspect.java
  src/main/java/io/oeid/mogakgo/common/event/handler/AchievementEventHandler.java
  src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementEventService.java
  src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementFacadeService.java
  src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementProgressService.java
  src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementService.java
  src/main/java/io/oeid/mogakgo/domain/achievement/application/dto/res/UserAchievementInfoRes.java
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/user/application/UserAchievementService.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
  src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserAchievementUpdateApiResponse.java
Labels: 🔄 Refactor, 🎯MVP2

#336 Refact/#335 notification tag
  src/main/java/io/oeid/mogakgo/domain/notification/domain/Notification.java
  src/main/java/io/oeid/mogakgo/domain/notification/domain/enums/NotificationTag.java
  src/main/resources/db/migration/V5_notification_tag.sql
Labels: 🔄 Refactor

#341 [BUG] 사용자의 업적 진행도를 포함한 업적 상세 조회 리스트에서 누적되는 업적에 대한 로직 수정
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementRepositoryCustomImpl.java
Labels: 🐞 Bug

#346 [BUG] 선택한 구역에 대한 프로필 리스트 조회에서 페이지네이션이 제대로 작동하지 않아요!
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
Labels: 🐞 Bug

#349 [BUG] 업적 달성 관련 오류 수정, 비회원 프로필 리스트 페이지네이션 오류 수정
  src/main/java/io/oeid/mogakgo/common/aop/AchievementEventAspect.java
  src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
Labels: 🐞 Bug

#352 Fix/#351 signup bug
  src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
  src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
  src/test/java/io/oeid/mogakgo/domain/user/application/UserServiceTest.java
  src/test/java/io/oeid/mogakgo/domain/user/domain/UserDomainTest.java
Labels: 🐞 Bug

#353 [FEAT] 프로젝트 종료시 채팅방 종료 스케쥴링 추가
  src/main/java/io/oeid/mogakgo/scheduler/FinishedProjectScheduler.java
Labels: ⭐️ Feat

#355 [REFACT] 사용자의 업적 상세 조회 시, 업적의 progressLevel 필드도 같이 전달하도록 추가
  src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementService.java
  src/main/java/io/oeid/mogakgo/domain/achievement/application/dto/res/UserAchievementInfoRes.java
  src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementRepositoryCustomImpl.java
  src/main/java/io/oeid/mogakgo/domain/achievement/presentation/dto/res/AchievementInfoAPIRes.java
  src/main/java/io/oeid/mogakgo/domain/achievement/presentation/dto/res/UserAchievementDetailAPIRes.java
Labels: 🔄 Refactor

#358 Docs/#357 readmd
  README.md
Labels: 📑 Docs, 💇🏻‍♀️ Style
